"""Load and adapt the original PyDracula light stylesheet.

Source:
https://github.com/Wanderson-Magalhaes/Modern_GUI_PyDracula_PySide6_or_PyQt6

The unmodified upstream stylesheet and MIT license are stored beside this
module. Only accent colors are remapped to the MakeSense workshop palette.
"""

from pathlib import Path


_HERE = Path(__file__).resolve().parent
_UPSTREAM_QSS = _HERE / "py_dracula_light.qss"

# Exact upstream PyDracula colors -> MakeSense-inspired colors.
_ACCENT_REPLACEMENTS = {
    "#bd93f9": "#0aa9e8",
    "#ff79c6": "#0aa9e8",
    "#6272a4": "#073f83",
    "#6a7cb1": "#0a58a7",
    "#5b6996": "#063770",
    "#5d6c99": "#09539f",
    "#495474": "#062f62",
    "#586796": "#074682",
    "#546391": "#052f64",
    "#7082b6": "#0a72b5",
    "#7284b9": "#0a72b5",
    "rgb(189, 147, 249)": "rgb(10, 169, 232)",  # purple -> MakeSense cyan
    "rgb(196, 161, 249)": "rgb(53, 187, 237)",
    "rgb(180, 141, 238)": "rgb(7, 63, 131)",    # pressed -> Delft blue
    "rgb(195, 155, 255)": "rgb(53, 187, 237)",
    "rgb(255, 121, 198)": "rgb(10, 169, 232)",  # pink -> MakeSense cyan
    "rgb(255, 170, 255)": "rgb(53, 187, 237)",
}


# PyDracula's original project uses object-name selectors generated by its
# Qt Designer file. These selectors bridge its visual language to this app's
# standard QMainWindow/QTabWidget structure.
_WORKSHOP_COMPATIBILITY_QSS = """
QMainWindow, QDialog {
    background-color: #f5f7fb;
}
QWidget {
    font-family: "Segoe UI";
}
QMenuBar {
    background-color: #ffffff;
    color: #263246;
    border-bottom: 1px solid #d9e0ea;
    padding: 4px;
}
QMenuBar::item {
    background: transparent;
    border-radius: 4px;
    padding: 7px 12px;
}
QMenuBar::item:selected, QMenu::item:selected {
    background-color: rgb(7, 63, 131);
    color: white;
}
QMenu {
    background-color: #ffffff;
    color: #263246;
    border: 1px solid #d9e0ea;
    padding: 5px;
}
QMenu::item {
    border-radius: 4px;
    padding: 7px 24px 7px 12px;
}
QTabWidget::pane {
    background-color: #f8f8f2;
    border: none;
    border-radius: 7px;
    left: -1px;
}
QTabBar {
    background-color: #073f83;
}
QTabBar::tab {
    background-color: #073f83;
    color: #dcecf8;
    border: none;
    border-left: 4px solid transparent;
    padding: 12px 18px;
    min-width: 180px;
    min-height: 48px;
    font-weight: 600;
}
QTabBar::tab:hover {
    background-color: #09539f;
    color: white;
}
QTabBar::tab:selected {
    background-color: #0aa9e8;
    color: white;
    border-left-color: #ffffff;
}
QGroupBox {
    background-color: #ffffff;
    color: #263246;
    border: none;
    border-radius: 7px;
    margin-top: 13px;
    padding: 17px 12px 12px 12px;
    font-size: 15px;
    font-weight: 600;
}
QGroupBox::title {
    subcontrol-origin: margin;
    left: 12px;
    padding: 0 6px;
}
QPushButton {
    background-color: #073f83;
    color: #ffffff;
    border: 2px solid #073f83;
    border-radius: 5px;
    padding: 7px 13px;
    font-weight: 600;
}
QPushButton:hover {
    background-color: #09539f;
    border-color: #0aa9e8;
}
QPushButton:pressed {
    background-color: rgb(7, 63, 131);
}
QPushButton:disabled {
    color: #8a96a8;
    background-color: #e5e9f0;
    border-color: #d3d9e3;
}
QLineEdit, QTextEdit, QPlainTextEdit, QComboBox,
QSpinBox, QDoubleSpinBox {
    background-color: #ffffff;
    color: #263246;
    border: 2px solid #d9e0ea;
    border-radius: 5px;
    padding: 6px;
    selection-background-color: rgb(10, 169, 232);
}
QLineEdit:hover, QTextEdit:hover, QPlainTextEdit:hover, QComboBox:hover,
QSpinBox:hover, QDoubleSpinBox:hover {
    border-color: rgb(64, 71, 88);
}
QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QComboBox:focus,
QSpinBox:focus, QDoubleSpinBox:focus {
    border-color: rgb(10, 169, 232);
}
QComboBox::drop-down {
    background-image: none;
    border-left: 1px solid #d9e0ea;
    width: 28px;
}
QComboBox::down-arrow {
    image: url("__CHEVRON_DOWN__");
    width: 12px;
    height: 7px;
}
QComboBox QAbstractItemView {
    color: #263246;
    background-color: #ffffff;
    selection-color: #ffffff;
    selection-background-color: #073f83;
}
QCheckBox::indicator {
    width: 18px;
    height: 18px;
    border-radius: 4px;
    background-color: #ffffff;
    border: 2px solid #708096;
}
QCheckBox::indicator:checked {
    background: #0aa9e8;
    background-image: url("__CHECKMARK__");
    background-position: center;
    background-repeat: no-repeat;
    border: 2px solid #0aa9e8;
}
QRadioButton::indicator {
    width: 18px;
    height: 18px;
    border-radius: 10px;
    background-color: #ffffff;
    border: 2px solid #708096;
}
QRadioButton::indicator:hover, QCheckBox::indicator:hover {
    border: 2px solid #0aa9e8;
}
QRadioButton::indicator:checked {
    background: #0aa9e8;
    background-image: url("__RADIO_DOT__");
    background-position: center;
    background-repeat: no-repeat;
    border: 2px solid #0aa9e8;
}
QCheckBox::indicator:disabled, QRadioButton::indicator:disabled {
    background: #e5e9f0;
    border: 2px solid #b5bfcc;
}
QSpinBox::up-button, QDoubleSpinBox::up-button {
    subcontrol-origin: border;
    subcontrol-position: top right;
    width: 22px;
    border-left: 1px solid #d9e0ea;
    border-bottom: 1px solid #e7ebf1;
    border-top-right-radius: 4px;
    background-color: #f5f7fb;
}
QSpinBox::down-button, QDoubleSpinBox::down-button {
    subcontrol-origin: border;
    subcontrol-position: bottom right;
    width: 22px;
    border-left: 1px solid #d9e0ea;
    border-bottom-right-radius: 4px;
    background-color: #f5f7fb;
}
QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover,
QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover {
    background-color: #eaf7fd;
}
QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {
    image: url("__CHEVRON_UP_SMALL__");
    width: 9px;
    height: 6px;
}
QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {
    image: url("__CHEVRON_DOWN_SMALL__");
    width: 9px;
    height: 6px;
}
QProgressBar {
    background-color: #e5e9f0;
    color: #263246;
    border: 1px solid #d3d9e3;
    border-radius: 5px;
    text-align: center;
}
QProgressBar::chunk {
    background-color: rgb(10, 169, 232);
    border-radius: 4px;
}
QStatusBar {
    background-color: #ffffff;
    color: #617086;
    border-top: 1px solid #d9e0ea;
}
"""


def load_makesense_theme() -> str:
    """Return upstream PyDracula QSS with MakeSense accent substitutions."""
    stylesheet = _UPSTREAM_QSS.read_text(encoding="utf-8")
    for upstream, makesense in _ACCENT_REPLACEMENTS.items():
        stylesheet = stylesheet.replace(upstream, makesense)
    # The upstream QSS expects its compiled Qt resource module. This project
    # uses standalone SVG icons, so prevent Qt from repeatedly resolving
    # resource URLs that are intentionally not registered here.
    stylesheet = stylesheet.replace(
        "background-image: url(:/icons/images/icons/cil-check-alt.png);",
        "background-image: none;",
    )
    stylesheet = stylesheet.replace(
        "background-image: url(:/icons/images/icons/cil-arrow-bottom.png);",
        "background-image: none;",
    )
    compatibility = _WORKSHOP_COMPATIBILITY_QSS
    icon_paths = {
        "__CHEVRON_DOWN__": (_HERE / "icons" / "chevron-down.svg").as_posix(),
        "__CHEVRON_UP_SMALL__": (_HERE / "icons" / "chevron-up-small.svg").as_posix(),
        "__CHEVRON_DOWN_SMALL__": (_HERE / "icons" / "chevron-down-small.svg").as_posix(),
        "__CHECKMARK__": (_HERE / "icons" / "checkmark.svg").as_posix(),
        "__RADIO_DOT__": (_HERE / "icons" / "radio-dot.svg").as_posix(),
    }
    for token, path in icon_paths.items():
        compatibility = compatibility.replace(token, path)
    return stylesheet + "\n" + compatibility


MAKESENSE_THEME = load_makesense_theme()
